package com.example.qnachlocal

const val LOAN_ID = "loan_id"
const val BENEFICIARY_NAME = "benef_name"
const val CUSTOMER_MOBILE = "cust_mob"
const val CUSTOMER_EMAIL = "cust_email"
const val IFSC_CODE = "ifsc_code"
const val CUSTOMER_BANK = "cust_bank"
const val BANK_ADDRESS = "bank_add"
const val CUSTOMER_ACC_NO = "cust_acc_no"
const val CONFIRM_ACC_NO = "confirm_acc_no"
const val ACCOUNT_TYPE = "acc_type"
const val CATEGORY = "category"
const val FREQUENCY = "freq"
const val FIRST_COLLECTION_DATE = "first_coll_date"
const val FINAL_COLLECTION_DATE = "final_coll_date"
const val ACH_AMT = "Ach_amt"